import { t } from '../../i18n'

export interface FilterValue {
    label: string
    value: string
}

export const gameModeFilters = [
    { label: t`Single player`, value: 'single-player' },
    { label: t`Multiplayer`, value: 'multiplayer' },
    { label: t`Co-operative`, value: 'co-operative' },
    { label: t`Massively Multiplayer Online (MMO)`, value: 'massively-multiplayer-online-mmo' },
    { label: t`Split screen`, value: 'split-screen' },
]

export const genreFilters = [
    { label: t`Shooter`, value: 'shooter' },
    { label: t`Indie`, value: 'indie' },
    { label: t`Puzzle`, value: 'puzzle' },
    { label: t`Quiz/Trivia`, value: 'quiz-trivia' },
    { label: t`Strategy`, value: 'strategy' },
    { label: t`Role-playing (RPG)`, value: 'role-playing-rpg' },
    { label: t`Adventure`, value: 'adventure' },
    { label: t`Platform`, value: 'platform' },
    { label: t`Arcade`, value: 'arcade' },
    { label: t`Simulator`, value: 'simulator' },
    { label: t`Racing`, value: 'racing' },
    { label: t`Fighting`, value: 'fighting' },
    { label: t`Sport`, value: 'sport' },
    { label: t`Point-and-click`, value: 'point-and-click' },
    { label: t`Turn-based strategy (TBS)`, value: 'turn-based-strategy-tbs' },
    { label: t`Pinball`, value: 'pinball' },
    { label: t`Visual Novel`, value: 'visual-novel' },
    { label: t`Real Time Strategy (RTS)`, value: 'real-time-strategy-rts' },
    { label: t`Music`, value: 'music' },
    { label: t`Tactical`, value: 'tactical' },
    { label: t`Hack and slash/Beat em up`, value: 'hack-and-slash-beat-em-up' },
]

export const platformFilters = [
    { label: 'PC (Microsoft Windows)', value: 'win' },
    { label: 'Linux', value: 'linux' },
    { label: 'Mac', value: 'mac' },

    { label: 'PlayStation 5', value: 'playstation-5' },
    { label: 'PlayStation 4', value: 'ps4--1' },
    { label: 'PlayStation 3', value: 'ps3' },
    { label: 'PlayStation 2', value: 'ps2' },
    { label: 'PlayStation', value: 'ps' },

    { label: 'Xbox One', value: 'xboxone' },
    { label: 'Xbox 360', value: 'xbox360' },
    { label: 'Xbox', value: 'xbox' },
    { label: 'Xbox Series X', value: 'xbox-series-x' },
    { label: 'Xbox Live Arcade', value: 'xla' },

    { label: 'Oculus VR', value: 'oculus-vr' },
    { label: 'PlayStation VR', value: 'playstation-vr' },
    { label: 'SteamVR', value: 'steam-vr' },

    { label: 'Android', value: 'android' },
    { label: 'iOS', value: 'ios' },
    { label: 'Windows Phone', value: 'winphone' },

    { label: 'Nintendo 3DS', value: '3ds' },
    { label: 'Nintendo DS', value: 'nds' },
    { label: 'Wii', value: 'wii' },
    { label: 'Windows Mixed Reality', value: 'windows-mixed-reality' },
]

export const remainingPlatformFilters = [
    { label: 'Analogue electronics', value: 'analogueelectronics' },
    { label: 'Ouya', value: 'ouya' },
    { label: 'Intellivision', value: 'intellivision' },
    { label: 'Commodore VIC-20', value: 'vic-20' },
    { label: 'Acorn Archimedes', value: 'acorn-archimedes' },
    { label: '3DO Interactive Multiplayer', value: '3do' },
    { label: 'Apple IIGS', value: 'apple-iigs' },
    { label: 'MSX2', value: 'msx2' },
    { label: 'Acorn Electron', value: 'acorn-electron' },
    { label: 'TRS-80 Color Computer', value: 'trs-80-color-computer' },
    { label: 'Dragon 32/64', value: 'dragon-32-slash-64' },
    { label: 'Family Computer Disk System', value: 'fds' },
    { label: 'Atari Jaguar', value: 'jaguar' },
    { label: 'Sega 32X', value: 'sega32' },
    { label: 'Vectrex', value: 'vectrex' },
    { label: 'Commodore PET', value: 'cpet' },
    { label: 'Sega CD', value: 'segacd' },
    { label: 'Sharp X68000', value: 'sharp-x68000' },
    { label: 'N-Gage', value: 'ngage' },
    { label: 'BlackBerry OS', value: 'blackberry' },
    { label: 'ColecoVision', value: 'colecovision' },
    { label: 'Odyssey', value: 'odyssey--1' },
    { label: 'WonderSwan', value: 'wonderswan' },
    { label: 'Hyper Neo Geo 64', value: 'hyper-neo-geo-64' },
    { label: 'Sharp X1', value: 'x1' },
    { label: 'Family Computer (FAMICOM)', value: 'famicom' },
    { label: 'Daydream', value: 'daydream' },
    { label: 'VC 4000', value: 'vc-4000' },
    { label: '1292 Advanced Programmable Video System', value: '1292-advanced-programmable-video-system' },
    { label: 'PC-8801', value: 'pc-8801' },
    { label: 'Philips CD-i', value: 'philips-cd-i' },
    { label: 'TurboGrafx-16/PC Engine', value: 'turbografx16--1' },
    { label: 'FM-7', value: 'fm-7' },
    { label: 'BBC Microcomputer System', value: 'bbcmicro' },
    { label: 'Super Nintendo Entertainment System (SNES)', value: 'snes--1' },
    { label: 'Sega Mega Drive/Genesis', value: 'smd' },
    { label: 'Nintendo DSi', value: 'nintendo-dsi' },
    { label: 'Game Boy Advance', value: 'gba' },
    { label: 'Mobile', value: 'mobile' },
    { label: 'Sega Saturn', value: 'saturn' },
    { label: 'WonderSwan Color', value: 'wonderswan-color' },
    { label: 'Nintendo Entertainment System (NES)', value: 'nes' },
    { label: 'Texas Instruments TI-99', value: 'ti-99' },
    { label: 'Wii U', value: 'wiiu' },
    { label: 'PlayStation Network', value: 'psn' },
    { label: 'PlayStation Vita', value: 'psvita' },
    { label: 'Nintendo Switch', value: 'switch' },
    { label: 'PC DOS', value: 'dos' },
    { label: 'Amiga', value: 'amiga' },
    { label: 'Atari ST/STE', value: 'atari-st' },
    { label: 'Apple II', value: 'appleii' },
    { label: 'PlayStation Portable', value: 'psp' },
    { label: 'Amiga CD32', value: 'amiga-cd32' },
    { label: 'Commodore C64/128', value: 'c64' },
    { label: 'Amstrad CPC', value: 'acpc' },
    { label: 'ZX Spectrum', value: 'zxs' },
    { label: 'Web browser', value: 'browser' },
    { label: 'MSX', value: 'msx' },
    { label: 'Neo Geo Pocket Color', value: 'neo-geo-pocket-color' },
    { label: 'Arcade', value: 'arcade' },
    { label: 'Atari 8-bit', value: 'atari8bit' },
    { label: 'Commodore 16', value: 'c16' },
    { label: 'Commodore Plus/4', value: 'c-plus-4' },
    { label: 'TRS-80', value: 'trs-80' },
    { label: 'Amstrad PCW', value: 'amstrad-pcw' },
    { label: 'Tatung Einstein', value: 'tatung-einstein' },
    { label: 'Super Famicom', value: 'sfam' },
    { label: 'Game Boy Color', value: 'gbc' },
    { label: 'Nintendo GameCube', value: 'ngc' },
    { label: 'Game Boy', value: 'gb' },
    { label: 'Nintendo 64', value: 'n64' },
    { label: 'Dreamcast', value: 'dc' },
    { label: 'Atari 2600', value: 'atari2600' },
    { label: 'Neo Geo MVS', value: 'neogeomvs' },
    { label: 'Neo Geo AES', value: 'neogeoaes' },
    { label: 'Neo Geo CD', value: 'neo-geo-cd' },
    { label: 'Sega Game Gear', value: 'gamegear' },
    { label: 'OnLive Game System', value: 'onlive-game-system' },
    { label: 'WiiWare', value: 'wiiware' },
    { label: 'Virtual Console (Nintendo)', value: 'vc' },
    { label: 'SG-1000', value: 'sg1000' },
    { label: 'Sega Master System', value: 'sms' },
    { label: 'Philips Videopac G7000', value: 'philips-videopac-g7000' },
]

export const themeFilters = [
    { label: t`Open world`, value: 'open-world' },
    { label: t`Stealth`, value: 'stealth' },
    { label: t`Action`, value: 'action' },
    { label: t`Science fiction`, value: 'science-fiction' },
    { label: t`Horror`, value: 'horror' },
    { label: t`Warfare`, value: 'warfare' },
    { label: t`Party`, value: 'party' },
    { label: t`Sandbox`, value: 'sandbox' },
    { label: t`Business`, value: 'business' },
    { label: t`Historical`, value: 'historical' },
    { label: t`Erotic`, value: 'erotic' },
    { label: t`Comedy`, value: 'comedy' },
    { label: t`Educational`, value: 'educational' },
    { label: t`Fantasy`, value: 'fantasy' },
    { label: t`Thriller`, value: 'thriller' },
    { label: t`Mystery`, value: 'mystery' },
    { label: t`Drama`, value: 'drama' },
    { label: t`4X (explore, expand, exploit, and exterminate)`, value: '4x-explore-expand-exploit-and-exterminate' },
    { label: t`Survival`, value: 'survival' },
    { label: t`Non-fiction`, value: 'non-fiction' },
    { label: t`Kids`, value: 'kids' },
]

export const categoryFilters = [
    { label: t`gameCategory.0`, value: '0' },
    { label: t`gameCategory.1`, value: '1' },
    { label: t`gameCategory.2`, value: '2' },
    { label: t`gameCategory.3`, value: '3' },
    { label: t`gameCategory.4`, value: '4' },
    { label: t`gameCategory.5`, value: '5' },
    { label: t`gameCategory.6`, value: '6' },
    { label: t`gameCategory.7`, value: '7' },
]
